name: {{cookiecutter.environment_name}}
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - fastapi=0.61.1
  - fiona=1.8.17
  - folium=0.11.0
  - geopandas=0.8.1
  - geopy=2.0.0
  - h3-py=3.6.4
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipywidgets=7.5.1
  - jenkspy=0.1.4
  - jinja2=2.11.2
  - jupyter-flex=0.6.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupytext=1.6.0
  - lifelines=0.25.4
  - matplotlib=3.3.2
  - nbconvert=6.0.7
  - networkx=2.5
  - notebook=6.1.4
  - numpy=1.19.1
  - osmnx=0.16.1
  - pandas=1.1.3
  - pandas-profiling=1.4.1
  - pip=20.2.4
  - python-snappy=0.5.4
  - pytz=2020.1
  - pyvis=0.1.8.2
  - qgrid=1.3.1
  - r-dplyr=0.8.0.1
  - r-ggplot2=3.1.1
  - r-irkernel=0.8.15
  - r-purrr=0.3.2
  - r-reticulate=1.16
  - r-stringr=1.4.0
  - r-tidyr=0.8.3
  - rpy2=3.3.2
  - rtree=0.9.4
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - statsmodels=0.12.0
  - voila=0.2.3
  - pip:
    - keplergl==0.2.1
    - uuid==1.30

